FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY apps/poller/package*.json ./apps/poller/
RUN npm ci

COPY . .
WORKDIR /app/apps/poller
ENV NODE_OPTIONS=--max-old-space-size=1536
RUN npm run build

# Runner
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/apps/poller/dist ./apps/poller/dist
COPY apps/poller/package*.json ./apps/poller/
WORKDIR /app/apps/poller
RUN npm ci --production

CMD ["node", "dist/index.js"]
