FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY apps/engine/package*.json ./apps/engine/
RUN npm ci

COPY . .
WORKDIR /app/apps/engine
ENV NODE_OPTIONS=--max-old-space-size=1536
RUN npm run build

# Runner
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/apps/engine/dist ./apps/engine/dist
COPY apps/engine/package*.json ./apps/engine/
WORKDIR /app/apps/engine
RUN npm ci --production

CMD ["node", "dist/index.js"]
