name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            REPO_DIR=exchange
            if [ -d "$REPO_DIR" ]; then rm -rf "$REPO_DIR"; fi
            git clone https://github.com/${{ github.repository }} $REPO_DIR
            cd $REPO_DIR
            docker compose down -v || true
            docker stop $(docker ps -aq) || true
            docker rm $(docker ps -aq) || true
            docker volume prune -f || true
            docker network prune -f || true
            docker compose build --no-cache
            docker compose up -d